### ISSUE TITLE
sha1 deprecation by homebrew

### ISSUE THREAD

**Issue by junkblocker** [jhawthorn/fzy#20]
```
Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Library/Taps/jhawthorn/homebrew-fzy/Formula/fzy.rb:6:in `<class:Fzy>'
Please report this to the jhawthorn/fzy tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Taps/jhawthorn/homebrew-fzy/Formula/fzy.rb:6:in `<class:Fzy>'
Please report this to the jhawthorn/fzy tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/jhawthorn/homebrew-fzy/Formula/fzy.rb:6:in `<class:Fzy>'
Please report this to the jhawthorn/fzy tap!
```

**Comment by srstevenson** [comment]
See https://github.com/jhawthorn/homebrew-fzy/pull/1.

**Comment by junkblocker** [comment]
Thanks @srstevenson , ``jhawthorn/fzy tap!`` mention made me miss the bug. Closing this here in favor of the one in the tap iteself.
